// src/components/ExplanationBubble.jsx

import React from "react";
import { motion } from "framer-motion";
import { Sparkles, Code2, AlertTriangle, Copy, Check } from "lucide-react";

export default function ExplanationBubble({ explanation, image, isError, onClear }) {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(explanation);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!explanation && !image) return null;

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className={`glass-premium rounded-[40px] border-white/10 overflow-hidden shadow-2xl relative ${
        isError ? "border-red-500/30 ring-1 ring-red-500/20" : ""
      }`}
    >
      {/* Decorative Glow */}
      {!isError && (
        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-brand to-transparent opacity-50" />
      )}

      <div className="p-8 space-y-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className={`p-2.5 rounded-2xl ${isError ? "bg-red-500/10 text-red-400" : "bg-brand/10 text-brand"}`}>
              {isError ? <AlertTriangle className="w-6 h-6" /> : <Sparkles className="w-6 h-6" />}
            </div>
            <div>
              <h3 className="text-xl font-bold font-display">
                {isError ? "System Diagnostics" : "Architectural Insight"}
              </h3>
              <p className="text-slate-400 text-xs tracking-wider uppercase font-bold">Generated by Neural Engine v4.0</p>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            {!isError && explanation && (
              <button 
                onClick={handleCopy}
                className="p-2.5 rounded-xl hover:bg-white/5 text-slate-400 hover:text-white transition-all flex items-center gap-2 text-sm border border-transparent hover:border-white/10"
              >
                {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                {copied ? "Copied" : "Copy Insight"}
              </button>
            )}
            <button 
              onClick={onClear}
              className="p-2.5 rounded-xl hover:bg-red-500/10 text-slate-400 hover:text-red-400 transition-all border border-transparent hover:border-red-500/20"
            >
              Clear
            </button>
          </div>
        </div>

        <div className="relative">
          {image ? (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="rounded-3xl overflow-hidden border border-white/10 bg-black/20 p-2"
            >
              <img src={image} alt="Code Logic Visualization" className="w-full h-auto rounded-2xl shadow-glow shadow-brand/10" />
              <div className="p-4 bg-brand/5 border-t border-white/5 flex items-center gap-3">
                <Code2 className="w-4 h-4 text-brand" />
                <span className="text-slate-400 text-sm">Flow diagram generated successfully</span>
              </div>
            </motion.div>
          ) : (
            <div className={`prose prose-invert max-w-none text-slate-300 leading-relaxed font-sans ${isError ? "text-red-300/80" : ""}`}>
              {explanation.split('\n').map((line, i) => (
                <p key={i} className="mb-4">
                  {line}
                  {i === explanation.split('\n').length - 1 && !isError && (
                    <motion.span 
                      animate={{ opacity: [1, 0] }}
                      transition={{ duration: 0.8, repeat: Infinity }}
                      className="inline-block w-1.5 h-4 bg-brand ml-1"
                    />
                  )}
                </p>
              ))}
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}
